# -*- mode: makefile -*-
#
# Makefile definitions included by the top Makefile

# The macro below is expanded when 'realpath' is not built-in.
# Built-in 'realpath' is available on GNU Make 3.81.
realpath = $(shell cd $(1); pwd)

ROOT_SRCDIR    := $(call realpath, C:/build/ws/BUILDTYPE/Release/LABEL/windows10/root)
ROOT_OBJDIR    := $(call realpath, C:/build/ws/BUILDTYPE/Release/LABEL/windows10/build)

ifndef ROOT_SRCDIR
$(error Error determining ROOT_SRCDIR)
endif
ifndef ROOT_OBJDIR
$(error Error determining ROOT_OBJDIR)
endif

# The macro below strips off the source dir path to make a relative path name
stripsrc = $(subst $(ROOT_SRCDIR)/,,$(1))

# This macro creates the list of pcm files to be passed to a library
# dictionary generation step, something like
#    $(call pcm_rootcling_opt,$(TREELIBDEPM))
pcm_rootcling_opt = -m lib/libCore_rdict.pcm $(addprefix -m ,$(subst $(SOEXT),_rdict.pcm,$1))

# This macro returns the name of the pcm corresponding to a library
#    $(call pcmname,$(TREELIB))
pcmname = $(subst .$(SOEXT),_rdict.pcm,$1)

# This macro returns the list of pcm's that are needed for a package
#    $(call pcmdep,TREE)
# the argument is the upper case name of the library (see the Module.mk)
pcmdep = lib/libCore_rdict.pcm $(subst .$(SOEXT),_rdict.pcm,$($1LIBDEPM))

# This macro builds the rootmap name starting from the library full path
#    $(call rmfName, TREELIB)
# the argument is the upper case name of the library (see the Module.mk)
rmfName = $(dir $1)$(subst .$(SOEXT),.rootmap,$(notdir $1))

# This macro returns the arguments to be passed to rootcling to properly
# generate the rootmap file
#    $(call rootmapModule, TREELIB)
# the argument is the upper case name of the library (see the Module.mk)
rootmapModule = -rml $(notdir $1) -rmf $(call rmfName, $1)

# This macro returns the argument to be passed to rootcling to
# properly setup the pcm
#    $(call dictModule,TREE)
# the argument is the upper case name of the library (see the Module.mk)
dictModule = -s $($1LIB) $(call rootmapModule, $($1LIB)) $(call pcm_rootcling_opt, $($1LIBDEPM))

# This macro is used to setup the rule where the pcm depends on the
# dictionary and the library's dependent pcm's
#    $(call pcmrule,TREE)
# the argument is the upper case name of the library (see the Module.mk)
pcmrule = $(call pcmname, $($1LIB)): $(call pcmdep, $1) $($1DS)

noop = @true # "Do nothing really, this is just to make the rule stick"

ARCH           := win32
HOST           := 

USECONFIG      := FALSE
MKLIBOPTIONS   := -v 6 16 00 

EXTRA_CFLAGS   := -Iinclude -nologo -IC:/build/ws/BUILDTYPE/Release/LABEL/windows10/root/build/win -FIw32pragma.h -FIsehmap.h -Zc:__cplusplus -MD -GR -EHsc- -W3 -wd4141 -wd4291 -wd4244 -wd4049 -D_WIN32 -D_XKEYCHECK_H -D_LIBCPP_HAS_NO_PRAGMA_SYSTEM_HEADER -DNOMINMAX -D_CRT_SECURE_NO_WARNINGS  -std=c++14
USERCONF_CFLAGS:= 
EXTRA_CXXFLAGS := -Iinclude -nologo -IC:/build/ws/BUILDTYPE/Release/LABEL/windows10/root/build/win -FIw32pragma.h -FIsehmap.h -Zc:__cplusplus -MD -GR -EHsc- -W3 -wd4141 -wd4291 -wd4244 -wd4049 -D_WIN32 -D_XKEYCHECK_H -D_LIBCPP_HAS_NO_PRAGMA_SYSTEM_HEADER -DNOMINMAX -D_CRT_SECURE_NO_WARNINGS  -std=c++14
USERCONF_CXXFLAGS:= 
EXTRA_LDFLAGS  := 
WERROR         := 
WINRTDEBUG     := no
CTORSINITARRAY := 
CXXMKDEPFLAGS  := 

GLBPATCHFLAGS  := 
EXTRA_AUTHFLAGS:=    

BINDIR         := $(ROOTSYS)/bin
LIBDIR         := $(ROOTSYS)/lib
INCDIR         := $(ROOTSYS)/include
ETCDIR         := $(ROOTSYS)/etc
MANDIR         := $(ROOTSYS)/man
DATADIR        := $(ROOTSYS)/.
ELISPDIR       := $(ROOTSYS)/emacs/site-lisp
TTFFONTDIR     := $(ROOTSYS)/fonts
MACRODIR       := $(ROOTSYS)/macros
SRCDIR         := $(ROOTSYS)/src
ICONPATH       := $(ROOTSYS)/icons
DOCDIR         := $(ROOTSYS)/.
TESTDIR        := $(ROOTSYS)/test
TUTDIR         := $(ROOTSYS)/tutorials
ACLOCALDIR     := $(ROOTSYS)/aclocal

BUILDX11       := 
X11INCDIR      := $(filter-out /usr/include, )
X11LIBDIR      := -L
XPMLIBDIR      := -L
XPMLIB         := 
XFTLIB         := no

BUILDCOCOA     := 
MACOSXVERS     := 
OSXSDK         := 
IOSVERS        := 
IOSSDK         := 

CXX11          := 
CXX14          := 
CXXMODULES     := OFF
LIBCXX         := 

EXPLICITLINK   := yes

ENABLETHREAD   := 
OSTHREADFLAG   := 
OSTHREADLIBDIR := 
OSTHREADLIB    := 

BUILTINFREETYPE:= 

BUILTINPCRE    := yes

BUILTINUNURAN  := 
UNURANLIBDIR   := 
UNURANLIBEXT   := 
UNURANLIB      := 
UNURANINCDIR   := $(filter-out /usr/include, )

BUILTINZLIB    := 
ZLIBLIBDIR     := 
ZLIBCLILIB     := $<TARGET_FILE:ZLIB>
ZLIBINCDIR     := $(filter-out /usr/include, C:/build/ws/BUILDTYPE/Release/LABEL/windows10/root/builtins/zlib)

BUILTINLZMA    := 
LZMALIBDIR     := 
LZMACLILIB     := 
LZMAINCDIR     := $(filter-out /usr/include, )

BUILTINLZ4     := 
LZ4LIBDIR      := 
LZ4CLILIB      := 
LZ4INCDIR      := $(filter-out /usr/include, )

BUILDGL        := 
OPENGLLIBDIR   := 
OPENGLULIB     := glu32
OPENGLLIB      := opengl32
OPENGLINCDIR   := $(filter-out /usr/include, )

BUILTINGL2PS   := 
GL2PSLIBDIR    := 
GL2PSLIB       := 
GL2PSINCDIR    := $(filter-out /usr/include, )

BUILDLDAP      := 
LDAPLIBDIR     := 
LDAPCLILIB     := 
LDAPINCDIR     := $(filter-out /usr/include, )

BUILDMYSQL     := 
MYSQLLIBDIR    := 
MYSQLCLILIB    := 
MYSQLINCDIR    := $(filter-out /usr/include, )

BUILDORACLE    := 
ORACLELIBDIR   := 
ORACLECLILIB   := 
ORACLEINCDIR   := $(filter-out /usr/include, )

BUILDPGSQL     := 
PGSQLLIBDIR    := 
PGSQLCLILIB    := 
PGSQLINCDIR    := $(filter-out /usr/include, )

BUILDSQLITE     := 
SQLITELIBDIR    := 
SQLITECLILIB    := 
SQLITEINCDIR    := $(filter-out /usr/include, C:/libs/sqlite3/3.25.3)

BUILDSAPDB     := 
SAPDBLIBDIR    := 
SAPDBCLILIB    := 
SAPDBINCDIR    := $(filter-out /usr/include, )

BUILDODBC      := 
ODBCLIBDIR     := 
ODBCCLILIB     := 
ODBCINCDIR     := $(filter-out /usr/include, )

BUILDGEOCAD    := 
OCCLIBDIR      := 
OCCLIB         := 
OCCINCDIR      := $(filter-out /usr/include, )

BUILDQT        := 
BUILDQTGSI     := 
QTLIBDIR       := 
QTLIB          := 
QTINCDIR       := $(filter-out /usr/include, )
QTVERS	       := 
QTMOCEXE       := 

BUILDRFIO      := 
SHIFTLIBDIR    := 
SHIFTLIB       := 
SHIFTINCDIR    := $(filter-out /usr/include, )
SHIFTCFLAGS    := 

BUILDCASTOR    := 
CASTORLIBDIR   := 
CASTORCLILIB   := 
CASTORINCDIR   := $(filter-out /usr/include, )
CASTORCFLAGS   := 

BUILDDAVIX      := 
DAVIXLIBDIR     := 
DAVIXCLILIB     := 
DAVIXINCDIR     := $(filter-out /usr/include, )

BUILDDCAP      := 
DCAPLIBDIR     := 
DCAPLIB        := 
DCAPINCDIR     := $(filter-out /usr/include, )

BUILDFTGL      := 
FTGLLIBDIR     := 
FTGLLIBS       := FTGL
FTGLINCDIR     := $(filter-out /usr/include, C:/build/ws/BUILDTYPE/Release/LABEL/windows10/root/graf3d/ftgl/inc)
ifeq ($(BUILDFTGL), yes)
FTGLCPPFLAGS   := -DBUILTIN_FTGL
endif

BUILDGLEW      := 
GLEWLIBDIR     := 
GLEWLIBS       := 
GLEWINCDIR     := $(filter-out /usr/include, )
ifeq ($(BUILDGLEW), yes)
GLEWCPPFLAGS   := -DBUILTIN_GLEW
endif

BUILDGFAL      := 
GFALLIBDIR     := 
GFALCLILIB     := 
GFALINCDIR     := $(filter-out /usr/include, )
SRMIFCEINCDIR  := $(filter-out /usr/include, )
GLIB2INCDIR    := $(filter-out /usr/include, )

BUILDGLITE     := 
GLITELIBDIR    := 
GAWLIB         := 
GAW_CPPFLAGS   := $(filter-out /usr/include, )

BUILDMEMSTAT   := 

BUILDBONJOUR   := 
DNSSDLIBDIR    := 
DNSSDLIB       := 
DNSSDINCDIR    := $(filter-out /usr/include, )

BUILDCHIRP     := 
CHIRPLIBDIR    := 
CHIRPCLILIB    := 
CHIRPINCDIR    := $(filter-out /usr/include, )

BUILDHDFS      := 
HDFSLIBDIR     := 
HDFSCLILIB     := 
HDFSINCDIR     := $(filter-out /usr/include, )

BUILDALIEN     := 
ALIENLIBDIR    := 
ALIENCLILIB    := 
ALIENINCDIR    := $(filter-out /usr/include, )

BUILDASIMAGE   := 
BUILTINASIMAGE := On
ASEXTRALIB     := 
ASEXTRALIBDIR  := 
ASJPEGINCDIR   := $(filter-out /usr/include, JPEG_INCLUDE_DIR-NOTFOUND)
ASPNGINCDIR    := $(filter-out /usr/include, )
ASTIFFINCDIR   := $(filter-out /usr/include, TIFF_INCLUDE_DIR-NOTFOUND)
ASINCDIR       := $(filter-out /usr/include, )
ASLIB          := 
ASLIBDIR       := 

BUILDFPYTHIA6    := 
FPYTHIA6LIBDIR   := 
FPYTHIA6LIB      := 
FPYTHIA6CPPFLAGS := 

BUILDFPYTHIA8    := 
FPYTHIA8INCDIR   := $(filter-out /usr/include, )
FPYTHIA8LIBDIR   := 
FPYTHIA8LIB      := 

BUILDFFTW3     := 
FFTW3LIBDIR    := 
FFTW3LIB       := 
FFTW3INCDIR    := $(filter-out /usr/include, )

BUILDFITSIO    := 
CFITSIOLIBDIR  := 
CFITSIOLIB     := 
CFITSIOINCDIR  := $(filter-out /usr/include, )

BUILDGVIZ      := 
GRAPHVIZLIBDIR := 
GRAPHVIZLIB    := 
GRAPHVIZINCDIR := $(filter-out /usr/include, )
GRAPHVIZCFLAGS := 

BUILDPYTHON    := 
PYTHONLIBDIR   := 
PYTHONLIB      := C:/Python27/libs/python27.lib
PYTHONINCDIR   := $(filter-out /usr/include, C:/Python27/include)
PYTHONLIBFLAGS := 
PYTHONEXE      := 

BUILDRUBY      := 
RUBYLIBDIR     := 
RUBYLIB        := 
RUBYINCDIR     := $(filter-out /usr/include, )

BUILDXML       := 
XMLLIBDIR      := 
XMLCLILIB      := 
XMLINCDIR      := $(filter-out /usr/include, LIBXML2_INCLUDE_DIR-NOTFOUND)

HASXRD         := 
XRDINCDIR      := 
XRDLIBDIR      := 
EXTRA_XRDFLAGS := 
XRDVERSION     := 
HASXRDUTILS    := 
XRDINCPRIVATE  := 
BUILDNETXNG    := no
BUILDXPROOFD   := 
BUILDXRDCLT    := 

SRPLIBDIR      := 
SRPLIB         := 
SRPINCDIR      := $(filter-out /usr/include, )

BUILDSRPUTIL   := 
SRPUTILLIBDIR  := 
SRPUTILLIB     := 
SRPUTILINCDIR  := $(filter-out /usr/include, )

AFSLIB         := 
AFSLIBDIR      := 
AFSINCDIR      := 
AFSEXTRACFLAGS := 
AFSSHARED      := 

ALLOCLIB       := 
ALLOCLIBDIR    := 

BUILDKRB5      := 
KRB5LIB        := 
KRB5LIBDIR     := 
KRB5INCDIR     := $(filter-out /usr/include, )
KRB5INIT       := 

COMERRLIB      := 
COMERRLIBDIR   := 

RESOLVLIB      := 

CRYPTOLIB      := 
CRYPTOLIBDIR   := 

BUILDGLOBUS    := 
GLOBUSLIB      := 
GLOBUSLIBDIR   := 
GLOBUSINCDIR   := $(filter-out /usr/include, )

BUILDMONALISA  := 
MONALISALIBDIR := 
MONALISACLILIB := 
MONALISAINCDIR := $(filter-out /usr/include, )

BUILDTBB       := 
TBBLIBDIR      := 
TBBLIB         := 
TBBINCDIR      := $(filter-out /usr/include, )

SSLLIB         := 
SSLLIBDIR      := 
SSLINCDIR      := $(filter-out /usr/include, )
SSLSHARED      := 

BUILTINLZMA    := 
LZMALIBDIR     := 
LZMACLILIB     := 
LZMAINCDIR     := $(filter-out /usr/include, )

SHADOWFLAGS    := Off
SHADOWLIB      :=
SHADOWLIBDIR   :=

BUILDMATHMORE  := 
GSLFLAGS       := $(filter-out -I/usr/include, )
GSLLIBDIR      := 
GSLLIBS        := 
GSLVERSION     := 

BUILTINLLVM    := 
LLVMCONFIG     := 

BUILDROOFIT    := 

BUILDMINUIT2   := 

BUILDUNURAN    := 

BUILDVC        := 
BUILDVDT       := 
AVXCXXFLAG     := 
SIMDCXXFLAGS   :=  
VCFLAGS        :=  

BUILDGDML      := 

BUILDTABLE     := 

BUILDTMVA      := 

BUILDAFDSMGRD  := 
AFDSMGRDAPMON  := 

BUILDHTTP      := 
USEFASCGI      := 
FASTCGIINCDIR  := 
ifeq ($(USEFASCGI), no)
FASTCGIFLAGS   := -DHTTP_WITHOUT_FASTCGI
endif

CPPUNIT        := 
GCCXML         := 

INSTALL        := cp -dpR
INSTALLDATA    := cp -dpR
INSTALLDIR     := mkdir -p
RSYNC          := rsync -au

BUILDR         := 
RLIBS          := 
RFLAGS         := 

ROOTDRPMREL    := 1
